### ISSUE TITLE
Keep more fields for uppervalid alerts

### ISSUE THREAD

**Issue by karpov-sv** [astrolabsoftware/fink-broker#778]
**Describe the issue**
We should keep more fields for `uppervalid` alerts that are available in the packets. 

**Expected behaviour**
We should at least keep the fields necessary for reconstructing apparent magnitudes - i.e. `isdiffpos`, `distnr`, `magnr`, `sigmagnr`.

**Actual behaviour**
Right now, the `uppervalid` is reusing the logic and list of fields from `upper` - see https://github.com/astrolabsoftware/fink-broker/blob/f2c00ca9b2fff8231033adfea9958430687eebec/bin/index_archival.py#L236. While for `upper` the rest of fields does not make much sense for us (and not much is available), for `uppervalid` everything is defined, apart from cutouts obviously.

The tables for `upper` and `uppervalid` are different, so why not expanding the latter slightly?.. It would allow to at least properly display them in the portal, properly report negative detections in the API, etc.

**Comment by JulienPeloton** [comment]
Thanks -- I agree it would be nice to have more fields to treat `uppervalid` the same way as other points. 

There is a subtle technical point here though. `uppervalid` measurements are contained in the history of each alert, so they are present for a very long time (30 days for ZTF). When we push data to the database index table, we do not check if this entry already exists -- we just overwrite its content. We can afford this because we do only a very small number of columns. But it would be overwhelming in terms of write operations if we do this for all columns. So unless we change the way data is pushed (i.e. pushing only truly new data), I would restrict the expansion of columns to the subset of columns necessary for reconstructing apparent magnitudes.

**Comment by karpov-sv** [comment]
Is some sort of index / unique constraint on `candid` field doable? It would help with not overwriting the data we already have (as `candid` should be unique per data point). Otherwise I agree that just a bare minimum of fields that we really need may be stored.

**Comment by JulienPeloton** [comment]
I was more thinking about having the collection of past measurements for an object. Starting from the most recent, checking if the next one (in the past) has an `uppervalid` status (which means does not satisfy the quality cuts). If yes, we push data, and continue to check the next one, until we find the next `valid` one that would stop the search. For most objects, there will be at most a few points to push (some bad quality alerts in between two valid alerts).
